# defines how points are allocated to teams in competition

title = "Points allocation"

# just rough for something
[match-result-points]
win = 2
tie_win = 1.9
tie_lose = 1
lose = 0
no_result = 1

# again, not thought through
[stage-multipliers]
first_round = 1
super_12 = 2
semi_finals = 8
finals = 16

# just ideas, will need fiddling
[bonus-points]
hat_trick = 0.5
century = 0.5
