name: generate-site-and-deploy
run-name: ${{ github.actor }} generated site files and deployed
on:
  [workflow_call]

jobs:
  generate-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Generate static site files
        run: python3 generate-html.py
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'competitions-site'

  deploy:
    runs-on: ubuntu-latest
    needs: [generate-files]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v1
