name: generate-site
run-name: ${{ github.actor }} generated site files
on:
  push:
    branches:
      - main

jobs:
  generate-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Generate static site files
        run: python3 generate-html.py
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'competitions-site'
      - uses: actions/deploy-pages@v1
