name: run-processing-scripts
run-name: ${{ github.actor }} updated output files
on:
  push:
    branches:
      - main

env:
  WRITE: true

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - name: Validate data
        run: Rscript validate.R
      - name: Generate data files
        run: Rscript matches-to-points.R
      - name: commit generated files
        run: |
          LAST_COMMIT_SHA="$(git rev-parse --short=7 HEAD)"
          # modified from https://stackoverflow.com/questions/25563455/how-do-i-get-last-commit-date-from-git-repository
          LAST_COMMIT_DATE="$(git log -1 --format="%at" | xargs -I{} date -d @{} +"%d-%m-%Y %H:%M")"
          git config --local user.name "ADBond"
          git config --local user.email "48208438+ADBond@users.noreply.github.com"
          git add competitions/mens_t20_world_cup_2022/data/generated
          git commit -m "Auto-generate outputs (from $LAST_COMMIT_SHA - $LAST_COMMIT_DATE)" || echo "No changes to commit"
      - name: push commit to main and deployed
        run: |
          git push origin main || echo "No changes to commit"
          git checkout -b deployed
          git push -u origin deployed || echo "No changes to push to deployment"
