name: run-processing-scripts
run-name: ${{ github.actor }} updated points file
on:
  push:
    branches:
      - gh-actions
      - main
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - uses: r-lib/actions/setup-renv@v2
      - run: Rscript matches-to-points.R
