name: run-processing-scripts
run-name: ${{ github.actor }} updated output files
on:
  push:
    branches:
      - main

env:
  WRITE: true

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - name: Validate data
        run: Rscript validate.R
      - name: Generate data files
        run: Rscript matches-to-points.R
      - name: commit generated files
        run: |
          git config --local user.name "ADBond"
          git config --local user.email "48208438+ADBond@users.noreply.github.com"
          git add mens_t20_world_cup_2021/data/generated
          git commit -m "Auto-generate outputs" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
